### ISSUE TITLE
There is not enough space in folder

### ISSUE THREAD

**Issue by dmj286** [jshridha/docker-blueiris#15]
I don't know if this is an appropriate place to ask this question, but I have been unable to figure it out.  I am new to docker and I think the issue is probably wine related, but I don't know who/where to ask for help.

When I bring up the container I get this error message (in a popup over vnc).
"There is not enough space in folder:C:\users\root\Application Data\Perspective Software\Blue Iris 5 5.0.6.9\install\  Please free some space and press Retry or press Cancel to abort the installation."

I am passing a shared nfs dataset (freenas) to the container with TB of space (-v /mnt/Shared:/root/prefix32:rw) and the VM (rancheros) running docker is installed on a virtual disk with ~200GB free.  Running df from bash attached to the container shows plenty of free space.  I have seen similar issues for wine, but not a solution that has allowed me to complete the blueiris installation.  Any help would be appreciated, thank you!

**Comment by dmj286** [comment]
Changed the prefix directory to a local path on the vm's disk image, and wine was happy with that, sorry for the clutter, and thank you for this project.

**Comment by jshridha** [comment]
I'm glad you're finding it useful. You may be able to mount the nfs drive using docker volumes using something the below in docker compose. There may be some typos in there, but you should get the general idea.

```yaml
version: '2'

services:

  blueiris:
    image: jshridha/blueiris
    ports:
      - "9000:8080"
      - "9001:5900"
      - "9002:81"
    volumes:
      - blueiris:/root/prefix32
      - /etc/localtime:/etc/localtime:ro

volumes:
  blueiris:
    driver: local
    driver_opts:
      type: nfs
      o: addr=freenas,rw,local_lock=all
      device: ":/mnt/pool1/blueirisr"
```
